os: Visual Studio 2015

version: 1.1.8.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-gs-x64.exe'
  - cmd: dotnet-sdk-2.0.0-win-gs-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\


build_script:
- appveyor-retry dotnet restore -v Minimal

- dotnet build .\src\LinqKit\LinqKit.csproj -c %CONFIGURATION%
- dotnet build .\src\LinqKit.EntityFramework\LinqKit.EntityFramework.csproj -c %CONFIGURATION%
- dotnet build .\src\LinqKit.Microsoft.EntityFrameworkCore\LinqKit.Microsoft.EntityFrameworkCore.csproj -c %CONFIGURATION%

- dotnet build .\tests\LinqKit.Tests\LinqKit.Tests.csproj -c %CONFIGURATION%
- dotnet build .\tests\LinqKit.Microsoft.EntityFrameworkCore.Tests\LinqKit.Microsoft.EntityFrameworkCore.Tests.csproj -c %CONFIGURATION%


test_script:
- dotnet test -c %CONFIGURATION% --no-build .\tests\LinqKit.Tests
- dotnet test -c %CONFIGURATION% --no-build .\tests\LinqKit.Microsoft.EntityFrameworkCore.Tests


artifacts:
- path: artifacts\**\*.*


cache:
- '%USERPROFILE%\.nuget\packages'